import type { Question } from "../types";

/**
 * Environmental — lead (EPA RRP) and asbestos. Trap-rich: the 1978 cutoff, the
 * 6 sq ft / 20 sq ft minor-repair exemption, "windows are always covered," and
 * the renovator refresher split (3 yrs without hands-on / 5 with).
 */
export const environmental: Question[] = [
  {
    id: "env-001",
    domain: "environmental",
    subtopic: "RRP — when it applies",
    difficulty: 1,
    stem: "The EPA Renovation, Repair and Painting (RRP) Rule applies to renovations that disturb paint in housing or child-occupied facilities built before what year?",
    options: ["1968", "1978", "1988", "2004"],
    answerIndex: 1,
    explanation:
      "The RRP Rule targets lead-based paint, which was banned for residential use in 1978. Renovations disturbing paint in pre-1978 housing and child-occupied facilities trigger lead-safe requirements.",
    citation: "40 CFR 745.82 — pre-1978 cutoff",
    tags: ["lead", "rrp"],
  },
  {
    id: "env-002",
    domain: "environmental",
    subtopic: "RRP — minor repair exemption",
    difficulty: 2,
    stem: "Which work in a pre-1978 home is most likely within the RRP 'minor repair and maintenance' exemption?",
    options: [
      "Disturbing 4 sq ft of interior paint in a room with no prohibited practices",
      "Replacing a window",
      "Sanding 30 sq ft of exterior siding",
      "Demolishing an interior wall",
    ],
    answerIndex: 0,
    explanation:
      "The minor-repair exemption covers disturbing 6 sq ft or less of interior paint per room (or 20 sq ft or less on the exterior) with no prohibited practices. Window replacement is ALWAYS covered regardless of size, so it never qualifies.",
    citation: "40 CFR 745.83 — 6 sq ft interior / 20 sq ft exterior",
    tags: ["lead", "rrp", "trap"],
  },
  {
    id: "env-003",
    domain: "environmental",
    subtopic: "RRP — window rule",
    difficulty: 2,
    stem: "Replacing a single window in a pre-1978 house disturbs only a small area of paint. Under the RRP Rule, is lead-safe certification required?",
    options: [
      "No, because the area is small",
      "Yes — window replacement is always a covered renovation regardless of the area disturbed",
      "Only if the homeowner requests it",
      "Only for commercial buildings",
    ],
    answerIndex: 1,
    explanation:
      "Window replacement is specifically excluded from the minor-repair exemption — it is always treated as a covered renovation in pre-1978 target housing, so lead-safe work practices and a certified firm/renovator are required.",
    citation: "40 CFR 745.83 — windows always covered",
    tags: ["lead", "rrp", "trap"],
  },
  {
    id: "env-004",
    domain: "environmental",
    subtopic: "RRP — firm certification term",
    difficulty: 2,
    stem: "How often must a firm renew its EPA RRP firm certification?",
    options: ["Every year", "Every 3 years", "Every 5 years", "Once, permanently"],
    answerIndex: 2,
    explanation:
      "EPA RRP firm certification must be renewed every 5 years. (Note Oregon's separate CCB lead-based paint renovation business license, which renews annually.)",
    citation: "40 CFR 745.89 — firm recertification every 5 years",
    tags: ["lead", "rrp"],
  },
  {
    id: "env-005",
    domain: "environmental",
    subtopic: "RRP — renovator refresher",
    difficulty: 3,
    stem: "A certified renovator takes a refresher course that does NOT include the hands-on component. How long is the renewed certification valid?",
    options: ["3 years", "5 years", "7 years", "It is invalid without hands-on"],
    answerIndex: 0,
    explanation:
      "A renovator refresher WITH the hands-on component renews for 5 years; a refresher WITHOUT hands-on renews for only 3 years. This split is a common trap versus older 'always 5 years' material.",
    citation: "40 CFR 745.90 — 3 yr (no hands-on) / 5 yr (with)",
    tags: ["lead", "rrp", "trap"],
  },
  {
    id: "env-006",
    domain: "environmental",
    subtopic: "Prohibited lead practices",
    difficulty: 2,
    stem: "Which practice is PROHIBITED when working on lead-based paint?",
    options: [
      "Using a HEPA vacuum",
      "Open-flame burning or torching, and uncontained power sanding/grinding of lead paint",
      "Wet-scraping with containment",
      "Posting warning signs",
    ],
    answerIndex: 1,
    explanation:
      "Open-flame burning/torching, machine sanding/grinding without HEPA exhaust control, and using a heat gun above 1100°F are prohibited because they spread lead dust and fumes. Lead-safe work relies on containment, HEPA tools, and verified cleaning.",
    citation: "40 CFR 745.85 — prohibited practices",
    tags: ["lead"],
  },
  {
    id: "env-007",
    domain: "environmental",
    subtopic: "Asbestos — who regulates",
    difficulty: 1,
    stem: "In Oregon, which agency primarily regulates asbestos abatement?",
    options: [
      "The CCB",
      "Oregon DEQ (Department of Environmental Quality)",
      "The county assessor",
      "The fire marshal",
    ],
    answerIndex: 1,
    explanation:
      "Oregon DEQ regulates asbestos. Friable asbestos abatement must be performed by a DEQ-licensed abatement contractor, and surveys must be done before many demolition/renovation projects.",
    citation: "OAR ch. 340 Div 248 — Oregon DEQ asbestos",
    tags: ["asbestos"],
  },
  {
    id: "env-008",
    domain: "environmental",
    subtopic: "Asbestos — survey requirement",
    difficulty: 2,
    stem: "Before demolishing or renovating, an asbestos survey by an accredited inspector is generally required for residential buildings built before what date (and for all commercial buildings)?",
    options: [
      "January 1, 1978",
      "January 1, 1990",
      "January 1, 2004",
      "Surveys are never required for homes",
    ],
    answerIndex: 2,
    explanation:
      "Oregon DEQ requires a pre-project asbestos survey for residential buildings built before January 1, 2004, and for all commercial buildings regardless of age, before demolition or renovation that could disturb asbestos-containing materials.",
    citation: "OAR 340-248-0270 — pre-2004 residential survey",
    tags: ["asbestos"],
  },
  {
    id: "env-009",
    domain: "environmental",
    subtopic: "Certified renovator on the job",
    difficulty: 2,
    stem: "For a covered RRP renovation, the certified firm must assign:",
    options: [
      "Any available worker",
      "A certified renovator responsible for the lead-safe work practices on that job",
      "An OSHA inspector",
      "The homeowner",
    ],
    answerIndex: 1,
    explanation:
      "A certified renovator must direct lead-safe work practices, train the other workers on site, and perform and verify cleaning. The firm must be EPA/Oregon certified and assign this person to each covered job.",
    citation: "40 CFR 745.89 — certified renovator on the job",
    tags: ["lead", "rrp"],
  },
  {
    id: "env-010",
    domain: "environmental",
    subtopic: "Renovate Right pamphlet",
    difficulty: 2,
    stem: "Before starting a covered RRP renovation, the firm must give the owner and occupants:",
    options: [
      "A copy of the bill",
      "The EPA 'Renovate Right' lead-hazard information pamphlet, and obtain acknowledgment",
      "A copy of the building code",
      "Nothing",
    ],
    answerIndex: 1,
    explanation:
      "RRP requires distributing the 'Renovate Right' pamphlet to owners and occupants before work begins, with documented acknowledgment, informing them of lead risks and their rights.",
    citation: "40 CFR 745.84 — pre-renovation education",
    tags: ["lead", "rrp"],
  },
  {
    id: "env-011",
    domain: "environmental",
    subtopic: "Cleaning verification",
    difficulty: 2,
    stem: "At the end of RRP work, the certified renovator must:",
    options: [
      "Leave the site immediately",
      "Repaint every surface",
      "Perform cleaning verification (the white-cloth check) to confirm the area is adequately clean",
      "Call the CCB for a final inspection",
    ],
    answerIndex: 2,
    explanation:
      "After cleanup, the certified renovator performs cleaning verification — wiping surfaces and comparing the cloth to the EPA verification card, repeating cleaning until it passes. It confirms lead dust was controlled.",
    citation: "40 CFR 745.85(b) — cleaning verification",
    tags: ["lead", "rrp"],
  },
  {
    id: "env-012",
    domain: "environmental",
    subtopic: "RRP recordkeeping",
    difficulty: 2,
    stem: "RRP compliance records (certifications, pamphlet acknowledgments, work documentation) must be retained for:",
    options: [
      "30 days",
      "3 years",
      "6 months",
      "No records are required",
    ],
    answerIndex: 1,
    explanation:
      "RRP firms must keep records demonstrating compliance — certifications, the signed pamphlet receipt, and documentation of lead-safe practices — for 3 years after a job.",
    citation: "40 CFR 745.86 — 3-year recordkeeping",
    tags: ["lead", "rrp", "recordkeeping"],
  },
  {
    id: "env-013",
    domain: "environmental",
    subtopic: "Construction stormwater permit",
    difficulty: 3,
    stem: "A construction project will disturb 2 acres of soil. In Oregon this generally requires:",
    options: [
      "No environmental permit",
      "A construction stormwater (1200-C) permit with an erosion and sediment control plan",
      "Only a building permit",
      "An automatic federal wetlands permit",
    ],
    answerIndex: 1,
    explanation:
      "Disturbing one acre or more (or part of a larger common plan of development) triggers Oregon DEQ's 1200-C construction stormwater permit, requiring an erosion and sediment control plan and inspections to keep sediment out of waterways.",
    citation: "Oregon DEQ — 1200-C construction stormwater permit",
    tags: ["stormwater", "oregon"],
  },
  {
    id: "env-014",
    domain: "environmental",
    subtopic: "Erosion control BMPs",
    difficulty: 2,
    stem: "Which is a common erosion and sediment control best practice (BMP) on a jobsite?",
    options: [
      "Letting bare soil drain into the street",
      "Silt fence, storm-drain inlet protection, and a stabilized construction entrance to keep sediment on site",
      "Burning cleared debris",
      "Pumping muddy water into storm drains",
    ],
    answerIndex: 1,
    explanation:
      "BMPs like silt fences, inlet protection, stabilized entrances, and covered stockpiles keep sediment (a regulated pollutant) out of storm systems and streams. Tracking mud into the street is a common violation.",
    citation: "Erosion & sediment control BMPs (Oregon DEQ)",
    tags: ["stormwater"],
  },
  {
    id: "env-015",
    domain: "environmental",
    subtopic: "Hazardous waste disposal",
    difficulty: 2,
    stem: "Leftover solvents, oil-based paints, and similar hazardous jobsite wastes must be:",
    options: [
      "Poured down the drain",
      "Buried on site",
      "Disposed of properly as hazardous/special waste — never dumped, drained, or put in the regular trash",
      "Burned in a barrel",
    ],
    answerIndex: 2,
    explanation:
      "Solvents, oil-based paint, adhesives, and similar wastes are hazardous and must go to proper disposal or recycling — never down drains, into storm systems, or buried. Improper disposal carries environmental liability.",
    citation: "Hazardous waste handling (EPA / Oregon DEQ)",
    tags: ["waste"],
  },
  {
    id: "env-016",
    domain: "environmental",
    subtopic: "Friable asbestos",
    difficulty: 2,
    stem: "'Friable' asbestos-containing material is especially dangerous because it:",
    options: [
      "Is too heavy to move",
      "Can be crumbled by hand, releasing fibers into the air",
      "Is always harmless",
      "Only exists in new buildings",
    ],
    answerIndex: 1,
    explanation:
      "Friable asbestos can be crumbled or pulverized by hand, readily releasing airborne fibers — the main inhalation hazard. Friable abatement must be done by DEQ-licensed abatement contractors under strict controls.",
    citation: "Oregon DEQ — friable asbestos / licensed abatement",
    tags: ["asbestos"],
  },
];
