import type { Question } from "../types";

/**
 * Building Exterior Shell — the water-management and weatherproofing knowledge
 * the exam tests: drainage planes, flashing, roofing, ventilation, moisture.
 */
export const exterior: Question[] = [
  {
    id: "ext-001",
    domain: "exterior",
    subtopic: "Weather-resistive barrier",
    difficulty: 2,
    stem: "The weather-resistive barrier (house wrap / building paper) behind siding is installed to:",
    options: [
      "Add structural strength",
      "Create a drainage plane that sheds water that gets past the siding, keeping the sheathing dry",
      "Improve appearance",
      "Replace the need for flashing",
    ],
    answerIndex: 1,
    explanation:
      "Siding isn't watertight; the WRB forms a secondary drainage plane that directs incidental water down and out, protecting the sheathing and framing. It complements — never replaces — proper flashing.",
    citation: "Water management — WRB (NASCLA)",
    tags: ["moisture"],
  },
  {
    id: "ext-002",
    domain: "exterior",
    subtopic: "Shingle-fashion lapping",
    difficulty: 2,
    stem: "Why are house wrap, flashing, and siding lapped 'shingle fashion' (upper pieces over lower)?",
    options: [
      "For appearance only",
      "So gravity directs water over the top of the piece below, not behind it",
      "To save material",
      "It is not actually required",
    ],
    answerIndex: 1,
    explanation:
      "Lapping upper layers over lower ones lets water run down the face and over the next piece, never getting directed behind it. Reverse-lapping ('backwards') funnels water into the wall — a classic failure.",
    citation: "Water management — lapping (NASCLA)",
    tags: ["moisture"],
  },
  {
    id: "ext-003",
    domain: "exterior",
    subtopic: "Window flashing",
    difficulty: 3,
    stem: "When flashing a window opening, the proper integration is generally:",
    options: [
      "Top (head) flashing tucked behind the WRB above; sill flashing first, then jambs, then head",
      "Caulk only, no flashing",
      "Head flashing on top of the WRB above the window",
      "Flash only the sill",
    ],
    answerIndex: 0,
    explanation:
      "Best practice: pan-flash the sill first, then jambs, then the head, with the WRB above lapping OVER the head flashing so water sheds outward. Relying on caulk alone, or lapping WRB under the head flashing, leads to leaks.",
    citation: "Fenestration flashing (NASCLA)",
    tags: ["flashing"],
  },
  {
    id: "ext-004",
    domain: "exterior",
    subtopic: "Kickout flashing",
    difficulty: 3,
    stem: "Where a roof eave meets a sidewall, a 'kickout' (diverter) flashing is used to:",
    options: [
      "Hold gutters in place",
      "Divert roof runoff away from the wall and into the gutter, preventing concentrated water in the wall",
      "Support the rafters",
      "Vent the attic",
    ],
    answerIndex: 1,
    explanation:
      "A kickout flashing at the roof-wall intersection diverts concentrated runoff into the gutter instead of behind the siding. Omitting it is a notorious cause of hidden wall and sheathing rot.",
    citation: "Roof-wall flashing (NASCLA)",
    tags: ["flashing"],
  },
  {
    id: "ext-005",
    domain: "exterior",
    subtopic: "Roof underlayment",
    difficulty: 1,
    stem: "Underlayment beneath roofing shingles serves to:",
    options: [
      "Add color",
      "Provide a secondary water barrier and protect the deck",
      "Replace the shingles",
      "Insulate the attic",
    ],
    answerIndex: 1,
    explanation:
      "Underlayment is a secondary barrier protecting the roof deck if water gets past the shingles and during installation. In cold/ice-prone areas, an ice-and-water membrane is added at eaves and valleys.",
    citation: "Roofing assemblies (NASCLA)",
    tags: ["roofing"],
  },
  {
    id: "ext-006",
    domain: "exterior",
    subtopic: "Step flashing",
    difficulty: 2,
    stem: "Where a sloped roof meets a vertical wall, the correct detail is:",
    options: [
      "A continuous bead of caulk",
      "Step flashing woven with each shingle course, integrated with the wall WRB",
      "Tar paper only",
      "Nothing — shingles seal themselves",
    ],
    answerIndex: 1,
    explanation:
      "Step flashing — individual pieces woven with each course and lapped by the wall's WRB/siding — channels water down the roof-wall junction. Caulk alone fails as it ages and is not a substitute.",
    citation: "Roof-wall flashing (NASCLA)",
    tags: ["flashing", "roofing"],
  },
  {
    id: "ext-007",
    domain: "exterior",
    subtopic: "Attic ventilation",
    difficulty: 2,
    stem: "Balanced attic ventilation (intake at soffits, exhaust near the ridge) helps to:",
    options: [
      "Increase heating bills",
      "Remove moisture and heat, reducing condensation, ice dams, and premature roof aging",
      "Support the roof structure",
      "Replace insulation",
    ],
    answerIndex: 1,
    explanation:
      "Balanced soffit-to-ridge ventilation flushes heat and moisture from the attic, helping prevent condensation, mold, and ice dams and extending roof life. Blocking soffit vents with insulation defeats it.",
    citation: "Attic ventilation (NASCLA)",
    tags: ["ventilation", "moisture"],
  },
  {
    id: "ext-008",
    domain: "exterior",
    subtopic: "Grading and drainage",
    difficulty: 2,
    stem: "Finished grade around a building should:",
    options: [
      "Slope toward the foundation",
      "Slope away from the foundation to carry surface water away",
      "Be perfectly flat",
      "Be below the basement floor",
    ],
    answerIndex: 1,
    explanation:
      "Grade must slope away from the building (commonly ~6 inches of fall within the first 10 feet) so surface water drains away rather than collecting against the foundation and finding its way inside.",
    citation: "Site drainage (NASCLA / ORSC)",
    tags: ["drainage"],
  },
  {
    id: "ext-009",
    domain: "exterior",
    subtopic: "Vapor retarders",
    difficulty: 3,
    stem: "A vapor retarder is generally placed:",
    options: [
      "On the cold side of the insulation",
      "Toward the warm-in-winter side of the assembly to limit moisture-laden air reaching cold surfaces",
      "It doesn't matter where",
      "Always on the exterior in all climates",
    ],
    answerIndex: 1,
    explanation:
      "In heating climates, vapor retarders go toward the warm (interior) side so warm, moist air can't reach cold surfaces and condense inside the assembly. Placement depends on climate — getting it wrong traps moisture.",
    citation: "Building science — vapor control (NASCLA)",
    tags: ["moisture"],
  },
  {
    id: "ext-010",
    domain: "exterior",
    subtopic: "Caulk vs flashing",
    difficulty: 2,
    stem: "Which statement about sealants (caulk) on the building exterior is correct?",
    options: [
      "Caulk is a permanent substitute for flashing",
      "Caulk supplements proper flashing but is not a primary water barrier; it degrades and needs maintenance",
      "Caulk should be the only line of defense",
      "Flashing is unnecessary if caulk is used",
    ],
    answerIndex: 1,
    explanation:
      "Sealants help, but they age, crack, and need upkeep — so they back up flashing and lapping, never replace them. Good water management relies on geometry (lapping, flashing, drainage), with caulk as a secondary measure.",
    citation: "Water management principles (NASCLA)",
    tags: ["moisture"],
  },
  {
    id: "ext-011",
    domain: "exterior",
    subtopic: "Deck ledger attachment",
    difficulty: 3,
    stem: "When attaching a deck ledger to a house, two critical requirements are:",
    options: [
      "Nails and a coat of paint",
      "Rated structural fasteners (lag screws or through-bolts, not just nails) AND flashing to keep water out of the wall",
      "Construction adhesive only",
      "Attaching directly to the siding",
    ],
    answerIndex: 1,
    explanation:
      "Deck-ledger failures cause collapses: the ledger must be fastened to the structure with rated lag screws or bolts (not nails) and flashed so water doesn't rot the band joist behind it. Never attach to siding alone.",
    citation: "ORSC — deck ledger attachment and flashing",
    tags: ["structure", "flashing"],
  },
  {
    id: "ext-012",
    domain: "exterior",
    subtopic: "Roof slope vs material",
    difficulty: 2,
    stem: "Standard asphalt shingles are generally NOT appropriate on:",
    options: [
      "A steep 8:12 roof",
      "A low-slope (nearly flat) roof, which needs a membrane system instead",
      "A 6:12 roof",
      "Any sloped roof",
    ],
    answerIndex: 1,
    explanation:
      "Asphalt shingles shed water by slope; below their minimum pitch they leak. Low-slope and flat roofs need membrane systems (EPDM, TPO, built-up). Match the roofing to the slope.",
    citation: "Roofing — slope and material (NASCLA)",
    tags: ["roofing"],
  },
  {
    id: "ext-013",
    domain: "exterior",
    subtopic: "Drip edge",
    difficulty: 2,
    stem: "Drip edge flashing at roof eaves and rakes:",
    options: [
      "Is purely decorative",
      "Directs water off the edge and away from the fascia and sheathing",
      "Holds the shingles down",
      "Replaces the underlayment",
    ],
    answerIndex: 1,
    explanation:
      "Drip edge guides runoff off the roof edge into the gutter and away from the fascia and sheathing, preventing edge rot and wind-driven water intrusion. Most codes require it.",
    citation: "Roofing details — drip edge (ORSC)",
    tags: ["roofing", "flashing"],
  },
  {
    id: "ext-014",
    domain: "exterior",
    subtopic: "Siding clearance to grade",
    difficulty: 2,
    stem: "Wood siding and trim should keep a clearance above the finished grade (soil) primarily to:",
    options: [
      "Improve appearance",
      "Meet zoning setbacks",
      "Prevent moisture wicking, rot, and pest entry at the base of the wall",
      "Save siding material",
    ],
    answerIndex: 2,
    explanation:
      "Keeping siding and trim clear of soil (commonly several inches) stops water from wicking up and pests from bridging in, protecting the wall base. Siding buried in soil or mulch rots quickly.",
    citation: "Cladding clearances (ORSC / NASCLA)",
    tags: ["moisture"],
  },
  {
    id: "ext-015",
    domain: "exterior",
    subtopic: "Crawlspace ground cover",
    difficulty: 2,
    stem: "A vapor-retarder ground cover over the soil in a crawlspace:",
    options: [
      "Is unnecessary",
      "Reduces moisture rising from the soil into the structure",
      "Provides structural support",
      "Eliminates all need for any foundation ventilation or conditioning",
    ],
    answerIndex: 1,
    explanation:
      "A ground-cover vapor retarder over crawlspace soil cuts the moisture that would otherwise migrate up into framing, lowering rot and mold risk. It works together with the crawlspace's ventilation or conditioning strategy.",
    citation: "Crawlspace moisture control (ORSC)",
    tags: ["moisture"],
  },
  {
    id: "ext-016",
    domain: "exterior",
    subtopic: "Galvanic corrosion",
    difficulty: 3,
    stem: "Putting dissimilar metals in contact in exterior flashing and fasteners (e.g., aluminum against copper, or plain steel in treated wood) risks:",
    options: [
      "Nothing at all",
      "Galvanic corrosion that prematurely degrades the connection",
      "Better water resistance",
      "Only a lower material cost",
    ],
    answerIndex: 1,
    explanation:
      "Dissimilar metals in contact with moisture form a galvanic cell, corroding the more active metal. Match metals, and use fasteners and flashing rated for pressure-treated lumber, which is corrosive to standard steel.",
    citation: "Material compatibility — galvanic corrosion (NASCLA)",
    tags: ["materials"],
  },
];
