import type { Question } from "../types";

/**
 * Construction Lien Law (ORS chapter 87). Heavily tested and deadline-driven —
 * the numbers (8 days, 75 days, 120 days) are the kind the open-book exam
 * expects you to find and apply fast.
 */
export const liens: Question[] = [
  {
    id: "liens-001",
    domain: "liens",
    subtopic: "Information Notice to Owner",
    difficulty: 2,
    stem: "An original contractor signs a residential improvement contract for $9,500. What lien-related document must be delivered to the owner?",
    options: [
      "Nothing — notices only apply to commercial work",
      "The Information Notice to Owner About Construction Liens",
      "A federal lien waiver",
      "A notice of intent to foreclose",
    ],
    answerIndex: 1,
    explanation:
      "On residential contracts where the price exceeds $2,000, the original contractor must give the owner the 'Information Notice to Owner About Construction Liens,' explaining how liens work and how to protect against them.",
    citation: "ORS 87.093 — Information Notice to Owner (> $2,000)",
    tags: ["notices"],
  },
  {
    id: "liens-002",
    domain: "liens",
    subtopic: "Information Notice threshold",
    difficulty: 1,
    stem: "The Information Notice to Owner is required when a residential contract price exceeds what amount?",
    options: ["$500", "$1,000", "$2,000", "$5,000"],
    answerIndex: 2,
    explanation:
      "The Information Notice to Owner is triggered when the residential contract price is greater than $2,000.",
    citation: "ORS 87.093 — $2,000 threshold",
    tags: ["notices", "thresholds"],
  },
  {
    id: "liens-003",
    domain: "liens",
    subtopic: "Notice of Right to a Lien — reachback",
    difficulty: 2,
    stem: "A material supplier delivers a Notice of Right to a Lien for a residential project. For labor or materials furnished before the notice is delivered, how far back does the notice protect the supplier's lien rights?",
    options: [
      "It protects everything from the start of the project",
      "Up to 8 days (not counting weekends/holidays) before delivery of the notice",
      "Up to 30 days before delivery",
      "It provides no protection for past deliveries",
    ],
    answerIndex: 1,
    explanation:
      "On residential work, the Notice of Right to a Lien protects materials and labor furnished from no earlier than 8 days (excluding Saturdays, Sundays, and holidays) before the notice is delivered. Delivering it promptly is what preserves lien rights for earlier deliveries.",
    citation: "ORS 87.021 / 87.023 — Notice of Right to a Lien, 8-working-day reachback",
    tags: ["notices", "deadlines"],
  },
  {
    id: "liens-004",
    domain: "liens",
    subtopic: "Perfecting the lien",
    difficulty: 2,
    stem: "Within how many days must a claimant file (perfect) a construction lien?",
    options: [
      "30 days after starting work",
      "75 days after the claimant last provided labor/materials, or after substantial completion — whichever is earlier",
      "120 days after the contract is signed",
      "1 year after the dispute arises",
    ],
    answerIndex: 1,
    explanation:
      "A claim of lien must be filed within 75 days after the claimant stops providing labor or materials, or within 75 days after the improvement is substantially complete, whichever occurs first.",
    citation: "ORS 87.035 — 75-day filing deadline",
    tags: ["deadlines"],
  },
  {
    id: "liens-005",
    domain: "liens",
    subtopic: "Foreclosing the lien",
    difficulty: 2,
    stem: "After a construction lien is recorded, within what period must suit to foreclose the lien be commenced?",
    options: ["30 days", "75 days", "120 days", "2 years"],
    answerIndex: 2,
    explanation:
      "A suit to foreclose a construction lien must be filed within 120 days after the lien claim is recorded; otherwise the lien expires.",
    citation: "ORS 87.055 — 120-day foreclosure deadline",
    tags: ["deadlines"],
  },
  {
    id: "liens-006",
    domain: "liens",
    subtopic: "Notice of intent to foreclose",
    difficulty: 2,
    stem: "Before filing suit to foreclose a residential lien, the claimant must give the owner a notice of intent to foreclose at least how many days in advance?",
    options: ["3 days", "10 days", "30 days", "No notice is required"],
    answerIndex: 1,
    explanation:
      "A notice of intent to foreclose must be delivered to the owner (and mortgagee, if any) at least 10 days before commencing a suit to foreclose.",
    citation: "ORS 87.057 — 10-day notice of intent to foreclose",
    tags: ["deadlines", "notices"],
  },
  {
    id: "liens-007",
    domain: "liens",
    subtopic: "What a lien attaches to",
    difficulty: 1,
    stem: "A perfected construction lien generally attaches to which of the following?",
    options: [
      "The contractor's tools and vehicles",
      "The improvement and the land on which it sits",
      "The owner's bank account directly",
      "The materials supplier's inventory",
    ],
    answerIndex: 1,
    explanation:
      "A construction lien attaches to the improvement and to the land (the owner's interest) reasonably necessary for its use, giving the claimant security against the property itself.",
    citation: "ORS 87.010 — lien attaches to improvement and land",
    tags: ["concepts"],
  },
  {
    id: "liens-008",
    domain: "liens",
    subtopic: "Purpose of lien waivers",
    difficulty: 2,
    stem: "Why does an owner or general contractor commonly collect lien waivers when paying subs and suppliers?",
    options: [
      "To increase the contract price",
      "To document that paid parties release their lien rights for the amounts paid, reducing double-payment risk",
      "Because the CCB issues them",
      "To extend the lien deadline",
    ],
    answerIndex: 1,
    explanation:
      "Lien waivers evidence that a paid subcontractor or supplier has released lien rights for the sums received. Collecting them as payments are made protects the owner/GC from paying twice if a lower-tier party later claims a lien.",
    citation: "ORS chapter 87 — lien waivers and payment practice",
    tags: ["payment", "risk"],
  },
  {
    id: "liens-009",
    domain: "liens",
    subtopic: "Who can claim a lien",
    difficulty: 1,
    stem: "Which party may generally claim a construction lien for unpaid value?",
    options: [
      "Only the general contractor",
      "Those who furnish labor, materials, equipment, or services that improve the property",
      "Only licensed architects",
      "Only the property owner",
    ],
    answerIndex: 1,
    explanation:
      "Persons who provide labor, materials, rental equipment, or certain services that contribute to the improvement of real property may claim a lien for the unpaid reasonable value — subject to the notice and timing rules.",
    citation: "ORS 87.010 — persons entitled to a lien",
    tags: ["concepts"],
  },
  {
    id: "liens-010",
    domain: "liens",
    subtopic: "Unlicensed claimant",
    difficulty: 3,
    stem: "A contractor who was unlicensed during the work attempts to record a construction lien. What is the likely result?",
    options: [
      "The lien is valid because lien law is separate from licensing",
      "The lien is unenforceable — an unlicensed contractor generally cannot perfect a lien",
      "The lien doubles as a civil penalty against the owner",
      "The CCB will record it on the contractor's behalf",
    ],
    answerIndex: 1,
    explanation:
      "Lien rights depend on lawful licensure. A contractor who was not properly licensed during the work generally cannot perfect or enforce a construction lien — one of the steepest costs of working unlicensed.",
    citation: "ORS 701.131 with ORS chapter 87",
    tags: ["licensing", "enforcement"],
  },
  {
    id: "liens-011",
    domain: "liens",
    subtopic: "Substantial completion",
    difficulty: 2,
    stem: "Why does the date of 'substantial completion' matter for lien filing?",
    options: [
      "It sets the warranty start date only",
      "It can start the 75-day clock to file a lien, even if minor punch-list work remains",
      "It cancels all prior notices",
      "It has no effect on lien deadlines",
    ],
    answerIndex: 1,
    explanation:
      "The 75-day filing window runs from when the claimant last furnished labor/materials OR from substantial completion, whichever is earlier. A claimant who waits for trivial punch-list items can miss the deadline measured from substantial completion.",
    citation: "ORS 87.035 — timing tied to substantial completion",
    tags: ["deadlines", "concepts"],
  },
  {
    id: "liens-012",
    domain: "liens",
    subtopic: "Owner's protection",
    difficulty: 2,
    stem: "What is one practical way an owner can reduce the risk of paying twice when lower-tier subs go unpaid?",
    options: [
      "Refuse to sign any contract",
      "Require lien waivers with payments and, where appropriate, use joint checks or verify subs/suppliers are paid",
      "Pay the entire price up front",
      "Avoid hiring licensed contractors",
    ],
    answerIndex: 1,
    explanation:
      "Owners protect themselves by conditioning payments on lien waivers, sometimes using joint checks to subs/suppliers, and confirming downstream parties are paid before releasing retainage — practices that close the gap lien law leaves open.",
    citation: "ORS chapter 87 — owner risk management",
    tags: ["payment", "risk"],
  },
  {
    id: "liens-013",
    domain: "liens",
    subtopic: "Who must give a Notice of Right to a Lien",
    difficulty: 2,
    stem: "Which party generally must deliver a Notice of Right to a Lien to preserve residential lien rights?",
    options: [
      "The original contractor who contracts directly with the owner",
      "Subcontractors and material suppliers who have no direct contract with the owner",
      "The owner",
      "The building official",
    ],
    answerIndex: 1,
    explanation:
      "Those without a direct contract with the owner — most subcontractors and suppliers — must deliver a Notice of Right to a Lien to preserve residential lien rights. An original contractor in direct privity with the owner generally need not serve it to protect its own claim.",
    citation: "ORS 87.021 — who must give the notice",
    tags: ["notices", "concepts"],
  },
  {
    id: "liens-014",
    domain: "liens",
    subtopic: "Lien priority",
    difficulty: 3,
    stem: "Why can a construction lien sometimes take priority over a mortgage that was recorded later?",
    options: [
      "Liens always lose to any mortgage",
      "Construction-lien priority generally relates back to when the improvement commenced, which can predate the mortgage",
      "The CCB ranks the competing claims",
      "Priority is decided alphabetically by claimant name",
    ],
    answerIndex: 1,
    explanation:
      "Construction-lien priority generally dates from when the improvement commenced (work visibly began or materials were first delivered). A mortgage recorded after that point can be subordinate — a risk lenders manage with inspections and title work.",
    citation: "ORS 87.025 — priority of construction liens",
    tags: ["priority"],
  },
  {
    id: "liens-015",
    domain: "liens",
    subtopic: "Bonding off a lien",
    difficulty: 2,
    stem: "How can an owner clear a disputed construction lien from the property's title while the dispute is resolved?",
    options: [
      "Ignore it until it expires",
      "Record a note asking the county to delete it",
      "Post a bond to release the lien from the property, substituting the bond as security",
      "Liens can never be removed before trial",
    ],
    answerIndex: 2,
    explanation:
      "An owner (or contractor) can substitute a surety bond for the property, releasing the lien from the title so a sale or refinance can proceed; the claimant then looks to the bond instead of the real estate.",
    citation: "ORS chapter 87 — release of lien by bond",
    tags: ["release", "owner"],
  },
  {
    id: "liens-016",
    domain: "liens",
    subtopic: "Where the lien is recorded",
    difficulty: 1,
    stem: "Where is a claim of construction lien recorded?",
    options: [
      "With the CCB",
      "In the county real-property records where the property is located",
      "With the IRS",
      "At the contractor's bank",
    ],
    answerIndex: 1,
    explanation:
      "A claim of lien is recorded in the real-property records of the county where the improved property sits, putting the world on notice of the encumbrance.",
    citation: "ORS 87.035 — recording the claim of lien",
    tags: ["procedure"],
  },
  {
    id: "liens-017",
    domain: "liens",
    subtopic: "Amount of the lien",
    difficulty: 2,
    stem: "The amount a claimant can lien for is generally limited to:",
    options: [
      "Any amount the claimant chooses",
      "The unpaid reasonable value of the labor, materials, or equipment furnished",
      "Triple the contract price as a penalty",
      "Only future work not yet performed",
    ],
    answerIndex: 1,
    explanation:
      "A lien secures the unpaid reasonable value of what was actually furnished to the improvement — not more. Inflating a lien can expose the claimant to liability and jeopardize the claim.",
    citation: "ORS 87.010 — lien for reasonable value",
    tags: ["concepts"],
  },
  {
    id: "liens-018",
    domain: "liens",
    subtopic: "Residential vs commercial notices",
    difficulty: 2,
    stem: "The 'Information Notice to Owner About Construction Liens' is primarily a requirement on which kind of project?",
    options: [
      "Residential improvement contracts above the dollar threshold",
      "Only public-works projects",
      "Only commercial high-rises",
      "Federal projects",
    ],
    answerIndex: 0,
    explanation:
      "The Information Notice to Owner is a residential consumer-protection requirement (contracts over $2,000). Commercial and public projects follow different notice and bonding schemes.",
    citation: "ORS 87.093 — residential Information Notice to Owner",
    tags: ["notices", "residential"],
  },
];
