import type { Question } from "../types";

/**
 * Subcontractors — selecting, contracting with, and managing subs, with the
 * Oregon-specific liability traps (uninsured-sub workers' comp, licensing).
 */
export const subcontractors: Question[] = [
  {
    id: "sub-001",
    domain: "subcontractors",
    subtopic: "Verify before hiring",
    difficulty: 2,
    stem: "Before putting a subcontractor to work, a prudent GC should verify all of the following EXCEPT:",
    options: [
      "Active CCB license",
      "Current liability insurance and workers' comp",
      "The sub's personal credit score",
      "Scope and price in a written subcontract",
    ],
    answerIndex: 2,
    explanation:
      "A GC should confirm the sub's active license, insurance, and workers' comp, and define scope/price in writing. A sub's personal credit score is not part of standard qualification.",
    citation: "Subcontractor management (NASCLA)",
    tags: ["qualification"],
  },
  {
    id: "sub-002",
    domain: "subcontractors",
    subtopic: "Uninsured sub workers' comp",
    difficulty: 3,
    stem: "A subcontractor with employees lacks workers' comp coverage. What is the GC's exposure in Oregon?",
    options: [
      "None — it is solely the sub's problem",
      "The GC may be held responsible for providing workers' comp coverage for the sub's workers",
      "The GC must pay the sub's income taxes",
      "The CCB automatically covers the workers",
    ],
    answerIndex: 1,
    explanation:
      "Oregon makes a GC responsible for an uninsured subcontractor's workers' compensation. Verifying each sub's current coverage before work begins is essential risk management.",
    citation: "ORS 656.029 — GC responsibility for uninsured sub",
    tags: ["workers comp", "oregon"],
  },
  {
    id: "sub-003",
    domain: "subcontractors",
    subtopic: "Unlicensed sub",
    difficulty: 2,
    stem: "What is a risk of hiring an unlicensed subcontractor?",
    options: [
      "No risk if the work is good",
      "Liability exposure for the GC, CCB complaints, and a sub who lacks lien rights and lawful collection remedies",
      "The sub automatically becomes licensed",
      "The GC's bond doubles",
    ],
    answerIndex: 1,
    explanation:
      "Using an unlicensed sub can expose the GC to liability and CCB action, and the unlicensed sub cannot lien or sue to collect — a chain of problems that can land back on the GC.",
    citation: "ORS 701.021 / 701.131",
    tags: ["licensing", "risk"],
  },
  {
    id: "sub-004",
    domain: "subcontractors",
    subtopic: "Flow-down clauses",
    difficulty: 2,
    stem: "A 'flow-down' (conduit) clause in a subcontract does what?",
    options: [
      "Lets the sub ignore the prime contract",
      "Binds the sub to applicable obligations the GC owes the owner under the prime contract",
      "Transfers the GC's license to the sub",
      "Eliminates the need for insurance",
    ],
    answerIndex: 1,
    explanation:
      "Flow-down clauses pass relevant prime-contract obligations (scope standards, schedule, dispute terms) down to the subcontractor, keeping the chain of responsibility consistent.",
    citation: "Subcontract administration (NASCLA)",
    tags: ["contracts"],
  },
  {
    id: "sub-005",
    domain: "subcontractors",
    subtopic: "Indemnification",
    difficulty: 2,
    stem: "An indemnification clause in a subcontract generally requires the sub to:",
    options: [
      "Pay the GC a bonus",
      "Defend/hold harmless the GC for losses arising from the sub's work or negligence",
      "Provide the GC's office supplies",
      "Waive all payment",
    ],
    answerIndex: 1,
    explanation:
      "Indemnification shifts certain risks: the sub agrees to defend and hold the GC harmless for claims arising out of the sub's work. (Oregon limits anti-indemnity for a party's own negligence in construction contracts.)",
    citation: "Subcontracts / ORS 30.140 (anti-indemnity)",
    tags: ["contracts", "risk"],
  },
  {
    id: "sub-006",
    domain: "subcontractors",
    subtopic: "Lien waivers from subs",
    difficulty: 2,
    stem: "Why should a GC collect lien waivers from subs and suppliers as it pays them?",
    options: [
      "To raise the contract price",
      "To document the release of lien rights for amounts paid and reduce double-payment risk to the owner/GC",
      "Because the CCB issues the waivers",
      "To extend the project schedule",
    ],
    answerIndex: 1,
    explanation:
      "Conditioning payments on lien waivers documents that paid subs/suppliers release their lien rights for those sums, protecting the owner and GC from paying twice if a lower-tier party later claims a lien.",
    citation: "ORS ch. 87 — lien waivers",
    tags: ["payment", "liens"],
  },
  {
    id: "sub-007",
    domain: "subcontractors",
    subtopic: "Insurance — additional insured",
    difficulty: 2,
    stem: "A GC commonly requires to be named as an 'additional insured' on a sub's liability policy in order to:",
    options: [
      "Pay the sub's premium",
      "Gain coverage under the sub's policy for claims arising from the sub's work",
      "Cancel the sub's policy",
      "Avoid carrying its own insurance",
    ],
    answerIndex: 1,
    explanation:
      "Being named additional insured extends the sub's policy to cover the GC for liability arising out of the sub's operations — a layer of protection beyond the GC's own coverage. A certificate of insurance evidences it.",
    citation: "Risk transfer — additional insured (NASCLA)",
    tags: ["insurance"],
  },
  {
    id: "sub-008",
    domain: "subcontractors",
    subtopic: "Independent contractor status",
    difficulty: 3,
    stem: "A GC pays a 'sub' who works only for the GC, uses the GC's tools, and has no business of their own. What is the risk?",
    options: [
      "None — anyone called a sub is a sub",
      "The worker may actually be an employee, creating payroll-tax and workers'-comp liability for misclassification",
      "The worker becomes the GC's partner",
      "The CCB issues the worker a license automatically",
    ],
    answerIndex: 1,
    explanation:
      "Labeling someone a subcontractor doesn't make it so. Failing Oregon's independent-contractor test (ORS 670.600) means the worker is really an employee — exposing the GC to back payroll taxes, penalties, and workers'-comp liability.",
    citation: "ORS 670.600 — independent contractor test",
    tags: ["classification", "oregon"],
  },
  {
    id: "sub-009",
    domain: "subcontractors",
    subtopic: "Scope coordination",
    difficulty: 1,
    stem: "A common cause of disputes and budget overruns when using multiple subs is:",
    options: [
      "Too much documentation",
      "Scope gaps or overlaps between subcontracts that leave work unassigned or double-bid",
      "Paying subs by check",
      "Holding a preconstruction meeting",
    ],
    answerIndex: 1,
    explanation:
      "Clear, complete scopes prevent gaps (work nobody bid) and overlaps (work bid twice). Coordinating scopes and schedules among subs is a core GC responsibility.",
    citation: "Project coordination (NASCLA)",
    tags: ["coordination"],
  },
  {
    id: "sub-010",
    domain: "subcontractors",
    subtopic: "Subcontractor reporting",
    difficulty: 1,
    stem: "Payments for services to an unincorporated subcontractor are typically reported to the IRS on:",
    options: ["Form W-2", "Form 1099-NEC", "Form I-9", "An OSHA 301"],
    answerIndex: 1,
    explanation:
      "Service payments to unincorporated independent subs are reported on Form 1099-NEC. Employees receive W-2s. (Confirm the current dollar reporting threshold for the tax year.)",
    citation: "IRS — Form 1099-NEC",
    tags: ["reporting"],
  },
  {
    id: "sub-011",
    domain: "subcontractors",
    subtopic: "Certificate of insurance",
    difficulty: 2,
    stem: "A certificate of insurance (COI) from a subcontractor is used to:",
    options: [
      "Guarantee the sub's profit",
      "Provide evidence the sub carries the required insurance, with limits and expiration dates",
      "Replace the subcontract",
      "Register the sub with the CCB",
    ],
    answerIndex: 1,
    explanation:
      "A COI documents that the sub carries required coverage (type, limits, expiration) and often names the GC as additional insured. Collect a current one before the sub starts and track expirations.",
    citation: "Risk transfer — certificates of insurance (NASCLA)",
    tags: ["insurance"],
  },
  {
    id: "sub-012",
    domain: "subcontractors",
    subtopic: "Pay-if-paid clauses",
    difficulty: 3,
    stem: "A subcontract says the GC pays the sub only 'if and when' the owner pays the GC. This 'pay-if-paid' clause:",
    options: [
      "Is always fully enforceable everywhere",
      "Attempts to shift the risk of owner nonpayment onto the sub, and its enforceability is limited or scrutinized in many states",
      "Means the sub never gets paid",
      "Is the same as a lien waiver",
    ],
    answerIndex: 1,
    explanation:
      "'Pay-if-paid' tries to make owner payment a condition of paying the sub (shifting nonpayment risk down), while 'pay-when-paid' is generally read only as a timing provision. Courts scrutinize pay-if-paid clauses, and some limit them — read payment terms carefully.",
    citation: "Subcontract payment clauses (NASCLA)",
    tags: ["payment", "risk"],
  },
  {
    id: "sub-013",
    domain: "subcontractors",
    subtopic: "Prompt payment",
    difficulty: 2,
    stem: "After the GC is paid by the owner for a sub's completed work, prompt-payment expectations generally require the GC to:",
    options: [
      "Hold the funds indefinitely",
      "Keep the sub's share as profit",
      "Pay the subcontractor its portion within the time the contract or law specifies",
      "Pay only after the warranty period ends",
    ],
    answerIndex: 2,
    explanation:
      "Prompt-payment principles require the GC to pass along a sub's earned portion within a defined window after being paid by the owner. Withholding earned funds invites claims and erodes sub relationships.",
    citation: "Prompt payment in construction contracts",
    tags: ["payment"],
  },
  {
    id: "sub-014",
    domain: "subcontractors",
    subtopic: "Retainage on subs",
    difficulty: 2,
    stem: "Retainage withheld from a subcontractor's progress payments is typically released:",
    options: [
      "Never",
      "After the sub's work is satisfactorily complete (often tied to overall project completion and acceptance)",
      "Before the work starts",
      "Only if the sub is unlicensed",
    ],
    answerIndex: 1,
    explanation:
      "Just as the owner withholds retainage from the GC, the GC commonly withholds it from subs, releasing it when the sub's work is accepted (often at project completion). Subs must plan cash flow around it.",
    citation: "Subcontract payment — retainage (NASCLA)",
    tags: ["payment"],
  },
  {
    id: "sub-015",
    domain: "subcontractors",
    subtopic: "Back-charge",
    difficulty: 2,
    stem: "A 'back-charge' against a subcontractor is:",
    options: [
      "A bonus paid to the sub",
      "A tax on the subcontract",
      "A deduction from the sub's payment for costs the GC incurred fixing the sub's deficient work or cleanup",
      "A type of lien",
    ],
    answerIndex: 2,
    explanation:
      "A back-charge offsets the sub's payment by documented costs the GC bore due to the sub's failure (rework, cleanup, damage). Document and notify per the subcontract; surprise back-charges spark disputes.",
    citation: "Subcontract administration — back-charges (NASCLA)",
    tags: ["payment"],
  },
  {
    id: "sub-016",
    domain: "subcontractors",
    subtopic: "Joint checks",
    difficulty: 2,
    stem: "Why might an owner or GC issue a 'joint check' payable to both a sub and the sub's material supplier?",
    options: [
      "To increase the contract price",
      "To help ensure the supplier is paid and reduce the risk of a supplier lien for unpaid materials",
      "To avoid paying the sub at all",
      "Because the CCB requires it",
    ],
    answerIndex: 1,
    explanation:
      "A check made out to both the sub and its supplier helps ensure the supplier actually gets paid for materials, lowering the risk that an unpaid lower-tier supplier files a lien against the property.",
    citation: "Payment risk — joint checks (NASCLA)",
    tags: ["payment", "liens"],
  },
];
