import type { Question } from "../types";

/**
 * Tax Basics + employee/independent-contractor rules. Stable percentages and
 * Oregon-specific rules only; volatile 2026 wage bases and the shifting
 * 1099-NEC dollar threshold are deliberately avoided to stay accurate.
 */
export const tax: Question[] = [
  {
    id: "tax-001",
    domain: "tax",
    subtopic: "Workers' comp threshold",
    difficulty: 2,
    stem: "When must an Oregon employer carry workers' compensation coverage?",
    options: [
      "Only after hiring the 4th employee",
      "From the first subject worker — there is no minimum employee count",
      "Only for employees earning over $50,000",
      "Only on commercial projects",
    ],
    answerIndex: 1,
    explanation:
      "Oregon requires workers' compensation coverage from the first subject worker — there is no small-employer exemption based on headcount. Genuine independent contractors under ORS 670.600 are not subject workers.",
    citation: "ORS 656.017 — coverage from first subject worker",
    tags: ["workers comp", "oregon"],
  },
  {
    id: "tax-002",
    domain: "tax",
    subtopic: "GC liability for uninsured sub",
    difficulty: 3,
    stem: "A general contractor hires a subcontractor who has employees but no workers' comp insurance. Who may be responsible for that coverage?",
    options: [
      "No one — it's the worker's problem",
      "The general contractor can be held responsible for the uninsured subcontractor's workers' comp",
      "Only the CCB",
      "The property owner automatically",
    ],
    answerIndex: 1,
    explanation:
      "Oregon makes a general contractor responsible for workers' compensation coverage of an uninsured subcontractor's workers. This is a strong reason to verify every sub carries current coverage before they set foot on site.",
    citation: "ORS 656.029 — GC responsibility for uninsured sub",
    tags: ["workers comp", "subcontractors"],
  },
  {
    id: "tax-003",
    domain: "tax",
    subtopic: "Independent contractor test",
    difficulty: 3,
    stem: "Under Oregon's independent-contractor standard (ORS 670.600), beyond being free from direction and control and properly licensed, the person must be 'customarily engaged in an independently established business,' shown by meeting at least how many of five factors?",
    options: ["1 of 5", "2 of 5", "3 of 5", "All 5"],
    answerIndex: 2,
    explanation:
      "The worker must satisfy at least 3 of the 5 factors (e.g., maintains a separate business location, bears risk of loss, serves two or more customers/advertises, has significant investment, can hire and fire). Misclassifying employees as contractors creates tax and workers'-comp liability.",
    citation: "ORS 670.600 — 3-of-5 independent-contractor test",
    tags: ["classification", "oregon"],
  },
  {
    id: "tax-004",
    domain: "tax",
    subtopic: "Social Security / Medicare",
    difficulty: 2,
    stem: "What are the employee-side FICA rates an employer withholds for Social Security and Medicare?",
    options: [
      "6.2% Social Security and 1.45% Medicare",
      "10% Social Security and 5% Medicare",
      "1.45% Social Security and 6.2% Medicare",
      "There is no Medicare withholding",
    ],
    answerIndex: 0,
    explanation:
      "Social Security is withheld at 6.2% (up to the annual wage base) and Medicare at 1.45% (no wage cap); the employer matches both. An additional 0.9% Medicare applies to high earners on the employee side only.",
    citation: "IRS Pub 15 — FICA rates",
    tags: ["payroll"],
  },
  {
    id: "tax-005",
    domain: "tax",
    subtopic: "Employer's payroll duty",
    difficulty: 1,
    stem: "What is an employer's basic obligation for employee payroll taxes?",
    options: [
      "Employees pay everything; the employer does nothing",
      "Withhold the employee share, add the employer share, and remit (deposit) the taxes to the government",
      "Pay taxes only once a year with no withholding",
      "Send cash directly to each employee for taxes",
    ],
    answerIndex: 1,
    explanation:
      "Employers must withhold income and FICA taxes from wages, add the employer's matching share, and deposit/remit those amounts to the IRS and state on schedule. Failing to remit trust-fund taxes carries serious personal liability.",
    citation: "IRS Pub 15 — withholding and deposits",
    tags: ["payroll"],
  },
  {
    id: "tax-006",
    domain: "tax",
    subtopic: "New-hire reporting",
    difficulty: 2,
    stem: "Within how many days must an Oregon employer report a newly hired employee to the state?",
    options: ["20 days", "60 days", "90 days", "Reporting is optional"],
    answerIndex: 0,
    explanation:
      "Oregon employers must report new hires to the state within 20 days, supporting child-support enforcement and program integrity.",
    citation: "ORS 25.790 — new-hire reporting (20 days)",
    tags: ["employees", "oregon"],
  },
  {
    id: "tax-007",
    domain: "tax",
    subtopic: "Independent contractor reporting form",
    difficulty: 1,
    stem: "Payments to an unincorporated independent contractor for services are generally reported on which form?",
    options: ["Form W-2", "Form 1099-NEC", "Form I-9", "Form 941"],
    answerIndex: 1,
    explanation:
      "Nonemployee compensation paid to independent contractors is reported on Form 1099-NEC; employee wages go on Form W-2. (The reporting dollar threshold has been changing — confirm the current figure for the relevant tax year.)",
    citation: "IRS — Form 1099-NEC",
    tags: ["classification", "reporting"],
  },
  {
    id: "tax-008",
    domain: "tax",
    subtopic: "Business structure — liability",
    difficulty: 2,
    stem: "Which business structure exposes the owner to UNLIMITED personal liability for business debts?",
    options: ["Sole proprietorship", "LLC", "Corporation", "S corporation"],
    answerIndex: 0,
    explanation:
      "A sole proprietorship provides no liability shield — the owner is personally liable for business debts and claims. LLCs and corporations create a separate legal entity that limits owners' personal exposure.",
    citation: "Business structures (NASCLA)",
    tags: ["structure"],
  },
  {
    id: "tax-009",
    domain: "tax",
    subtopic: "Business structure — S corp",
    difficulty: 2,
    stem: "A key feature distinguishing an S corporation from a C corporation is:",
    options: [
      "S corps pay corporate income tax twice",
      "S-corp income generally passes through to shareholders, avoiding the C corp's double taxation",
      "S corps cannot have any employees",
      "S corps require no records",
    ],
    answerIndex: 1,
    explanation:
      "An S corporation generally passes income through to shareholders' personal returns, avoiding the double taxation a C corporation faces (taxed at the corporate level and again on dividends). S corps have eligibility limits, such as a cap on the number of shareholders.",
    citation: "Business structures / taxation (NASCLA)",
    tags: ["structure"],
  },
  {
    id: "tax-010",
    domain: "tax",
    subtopic: "Recordkeeping retention",
    difficulty: 2,
    stem: "How long should an employer generally retain payroll tax records under IRS rules?",
    options: [
      "Until the next payday",
      "At least 4 years",
      "Records never need to be kept",
      "Exactly 1 year",
    ],
    answerIndex: 1,
    explanation:
      "The IRS expects employment tax records to be kept at least 4 years. Construction's long liability tail (defect statutes) makes keeping project and financial records even longer a prudent practice.",
    citation: "IRS — payroll record retention (4 years)",
    tags: ["recordkeeping"],
  },
  {
    id: "tax-011",
    domain: "tax",
    subtopic: "Oregon sales tax",
    difficulty: 1,
    stem: "What statewide general sales tax applies to materials a contractor buys in Oregon?",
    options: [
      "A 7% statewide sales tax",
      "Oregon has no statewide general sales tax",
      "A 10% construction sales tax",
      "A 5% use tax on all tools",
    ],
    answerIndex: 1,
    explanation:
      "Oregon has no statewide general sales tax. Contractors still owe income, payroll, and other taxes, and pay sales tax on purchases made in states that have one — but Oregon purchases are not subject to a state sales tax.",
    citation: "Oregon — no statewide sales tax",
    tags: ["oregon"],
  },
  {
    id: "tax-012",
    domain: "tax",
    subtopic: "Self-employment tax",
    difficulty: 2,
    stem: "A sole proprietor pays self-employment tax (Social Security + Medicare) at a combined rate of about:",
    options: ["7.65%", "10%", "15.3%", "25%"],
    answerIndex: 2,
    explanation:
      "Self-employment tax is about 15.3% (12.4% Social Security up to the wage base + 2.9% Medicare) because the self-employed person pays both the employee and employer halves. Half of it is deductible for income-tax purposes.",
    citation: "IRS — self-employment tax (Schedule SE)",
    tags: ["self-employment"],
  },
  {
    id: "tax-013",
    domain: "tax",
    subtopic: "Quarterly payroll return",
    difficulty: 1,
    stem: "Which federal form does an employer file quarterly to report withheld income tax and FICA?",
    options: ["Form 941", "Form W-4", "Form 1040", "Form SS-4"],
    answerIndex: 0,
    explanation:
      "Employers report wages, withheld income tax, and FICA quarterly on Form 941, reconciling what was withheld and deposited. (Very small employers may file annually on Form 944 if the IRS assigns it.)",
    citation: "IRS — Form 941 (quarterly)",
    tags: ["payroll"],
  },
  {
    id: "tax-014",
    domain: "tax",
    subtopic: "Estimated taxes",
    difficulty: 2,
    stem: "A self-employed contractor with no withholding generally must:",
    options: [
      "Pay all tax once on April 15 with no penalty",
      "Make quarterly estimated tax payments during the year",
      "Never pay until audited",
      "Pay only state tax, never federal",
    ],
    answerIndex: 1,
    explanation:
      "Without an employer withholding for them, self-employed contractors must pay estimated taxes quarterly to cover income and self-employment tax. Skipping them triggers underpayment penalties even if the balance is paid at year-end.",
    citation: "IRS — estimated tax (Form 1040-ES)",
    tags: ["self-employment"],
  },
  {
    id: "tax-015",
    domain: "tax",
    subtopic: "Unemployment insurance",
    difficulty: 2,
    stem: "State and federal unemployment insurance taxes (SUTA/FUTA) are:",
    options: [
      "Withheld from the employee's paycheck",
      "Paid by the employer, generally not deducted from employee wages",
      "Optional for construction employers",
      "Collected by the CCB",
    ],
    answerIndex: 1,
    explanation:
      "Unemployment insurance (FUTA federally, SUTA through the Oregon Employment Department) is generally an employer-paid tax, not withheld from workers. Rates vary with the employer's experience rating (claims history).",
    citation: "IRS FUTA / Oregon Employment Department SUTA",
    tags: ["payroll", "employer"],
  },
  {
    id: "tax-016",
    domain: "tax",
    subtopic: "Oregon Corporate Activity Tax",
    difficulty: 3,
    stem: "Oregon's Corporate Activity Tax (CAT) generally applies to a business once its Oregon commercial activity exceeds:",
    options: ["$10,000", "$100,000", "$1,000,000", "There is no such tax"],
    answerIndex: 2,
    explanation:
      "Oregon's CAT applies to commercial activity above $1 million (with a registration trigger at $750,000). Higher-volume contractors must plan for it; small operations typically fall below the threshold. Verify current figures, as thresholds can change.",
    citation: "Oregon Corporate Activity Tax (ORS chapter 317A)",
    tags: ["oregon", "business tax"],
  },
];
